#!/bin/sh
mount -a
insmod /lib/modules/2.6.21/kernel/drivers/dray_hw.ko > /dev/null 2>&1
mkdir -p /var/run
cat /etc_ro/motd
radius.sh init
nvram_daemon&
/sbin/burn_in.sh
goahead&
tr069_client&
/bin/dray_fwup &

#for telnet debugging
telnetd

#/sbin/apmc.sh

#for syslogd
mkdir -p /var/log

